#requires -Version 7.0

<#
.SYNOPSIS
Restores SmartCache against the pinned upstream Diginsight release.

.DESCRIPTION
Downloads and verifies the pinned upstream GitHub Release, writes the git-ignored src/NuGet.config
overlay that gives Diginsight.* local priority in both CLI and IDE builds, and restores the solution.

Update  - developer surface: default package cache, --force-evaluate, refreshes lock files.
Locked  - verification surface: isolated cache, --no-http-cache, --locked-mode.
Clean   - removes the overlay, the downloaded feed, and the isolated cache.
#>

[CmdletBinding()]
param(
    [ValidateSet('Update', 'Locked', 'Clean')]
    [string] $Mode = 'Update',

    [string] $Name = 'telemetry',

    # Offline validation only: treat an already staged local release directory as the release.
    [string] $FromDirectory,

    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Dot-sourcing runs the other script's param block in this scope, resetting same-named arguments.
$RequestedName = $Name
$RequestedFromDirectory = $FromDirectory
$RequestedForce = [bool] $Force

. (Join-Path $PSScriptRoot 'Get-UpstreamPackages.ps1')

$RepositoryRoot = Get-FullPath (Join-Path $PSScriptRoot '..')
$SolutionPath = Join-Path $RepositoryRoot 'src' 'Diginsight.SmartCache.slnx'
$OverlayPath = Join-Path $RepositoryRoot 'src' 'NuGet.config'
$RootConfigPath = Join-Path $RepositoryRoot 'NuGet.Config'
$UpstreamRoot = Join-Path $RepositoryRoot 'artifacts' 'upstream'
$RestoreCacheRoot = Join-Path $RepositoryRoot 'artifacts' 'restore-cache'

function Get-CorporateProxySource {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string] $Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Committed NuGet configuration '$Path' does not exist."
    }

    $document = [System.Xml.XmlDocument]::new()
    $document.XmlResolver = $null
    $document.Load($Path)

    $nodes = @($document.SelectNodes("/configuration/packageSources/add[@value]"))
    $remote = @($nodes | Where-Object { ([string] $_.GetAttribute('value')).StartsWith('http', [System.StringComparison]::OrdinalIgnoreCase) })
    if ($remote.Count -ne 1) {
        throw "Expected exactly one remote package source in '$Path'; found $($remote.Count)."
    }

    $value = [string] $remote[0].GetAttribute('value')
    if ($value -match '(?i)nuget\.org') {
        throw "Committed NuGet configuration must not reference nuget.org directly; found '$value'."
    }

    return [pscustomobject]@{
        Key   = [string] $remote[0].GetAttribute('key')
        Value = $value
    }
}

function Write-UpstreamOverlay {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string] $Path,

        [Parameter(Mandatory)]
        [string] $FeedPath,

        [Parameter(Mandatory)]
        [object] $Pin,

        [Parameter(Mandatory)]
        [object] $Proxy
    )

    $sourceKey = "upstream-$($Pin.Name)"
    $document = [System.Xml.XmlDocument]::new()
    $null = $document.AppendChild($document.CreateXmlDeclaration('1.0', 'utf-8', $null))
    $null = $document.AppendChild($document.CreateComment(
        " Generated by eng/Restore-WithUpstream.ps1 for $($Pin.Repository) $($Pin.SourceTag). Do not commit. "))

    $configuration = $document.AppendChild($document.CreateElement('configuration'))

    $packageSources = $configuration.AppendChild($document.CreateElement('packageSources'))
    $null = $packageSources.AppendChild($document.CreateElement('clear'))

    $localSource = $packageSources.AppendChild($document.CreateElement('add'))
    $localSource.SetAttribute('key', $sourceKey)
    $localSource.SetAttribute('value', (Get-FullPath $FeedPath))

    $proxySource = $packageSources.AppendChild($document.CreateElement('add'))
    $proxySource.SetAttribute('key', $Proxy.Key)
    $proxySource.SetAttribute('value', $Proxy.Value)
    $proxySource.SetAttribute('protocolVersion', '3')

    $mapping = $configuration.AppendChild($document.CreateElement('packageSourceMapping'))

    $localMapping = $mapping.AppendChild($document.CreateElement('packageSource'))
    $localMapping.SetAttribute('key', $sourceKey)
    $localPattern = $localMapping.AppendChild($document.CreateElement('package'))
    $localPattern.SetAttribute('pattern', $Pin.PackageSourceMappingPattern)

    $proxyMapping = $mapping.AppendChild($document.CreateElement('packageSource'))
    $proxyMapping.SetAttribute('key', $Proxy.Key)
    $proxyPattern = $proxyMapping.AppendChild($document.CreateElement('package'))
    $proxyPattern.SetAttribute('pattern', '*')

    $settings = [System.Xml.XmlWriterSettings]::new()
    $settings.Indent = $true
    $settings.IndentChars = '  '
    $settings.Encoding = [System.Text.UTF8Encoding]::new($false)

    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try {
        $document.Save($writer)
    }
    finally {
        $writer.Dispose()
    }

    Write-Host "Wrote package source overlay '$Path' mapping '$($Pin.PackageSourceMappingPattern)' to '$FeedPath'."
}

function Assert-PinnedVersionProperty {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object] $Pin
    )

    $path = Join-Path $RepositoryRoot $Pin.VersionPropertyFile
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Version property file '$path' does not exist."
    }

    $document = [System.Xml.XmlDocument]::new()
    $document.XmlResolver = $null
    $document.Load($path)

    $nodes = @($document.SelectNodes("//*[local-name()='$($Pin.VersionProperty)']"))
    if ($nodes.Count -ne 1) {
        throw "Expected exactly one '$($Pin.VersionProperty)' element in '$path'; found $($nodes.Count)."
    }

    $declared = ConvertTo-NormalizedPackageVersion -Version ([string] $nodes[0].InnerText)
    if ($declared -cne $Pin.PackageVersion) {
        throw "'$($Pin.VersionProperty)' is '$declared' but the pinned upstream version is '$($Pin.PackageVersion)'. Update '$($Pin.VersionPropertyFile)' or eng/upstream-releases.json."
    }

    Write-Host "'$($Pin.VersionProperty)' matches the pinned upstream version $declared."
}

function Assert-UpstreamProvenance {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string] $PackageCachePath,

        [Parameter(Mandatory)]
        [string] $FeedPath,

        [Parameter(Mandatory)]
        [object] $Pin
    )

    if (-not (Test-Path -LiteralPath $PackageCachePath -PathType Container)) {
        throw "Package cache '$PackageCachePath' does not exist after restore."
    }

    $expectedSource = Get-FullPath $FeedPath
    $manifest = Get-Content -LiteralPath (Join-Path $expectedSource 'release-manifest.json') -Raw | ConvertFrom-Json -Depth 20
    $upstreamIds = @($manifest.assets |
        Where-Object { [string]::Equals([string] $_.role, 'package', [System.StringComparison]::Ordinal) } |
        ForEach-Object { [string] $_.packageId } |
        Sort-Object -Unique)

    $checked = 0
    foreach ($id in $upstreamIds) {
        # Only the pinned version is in scope; other cached versions belong to unrelated work.
        $metadataPath = Join-Path $PackageCachePath $id.ToLowerInvariant() $Pin.PackageVersion.ToLowerInvariant() '.nupkg.metadata'
        if (-not (Test-Path -LiteralPath $metadataPath -PathType Leaf)) {
            continue
        }

        $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json -Depth 10
        if ($null -eq $metadata.PSObject.Properties['source']) {
            throw "Package '$id' $($Pin.PackageVersion) has no recorded source; cannot prove upstream provenance."
        }

        $actualSource = ([string] $metadata.source).TrimEnd('\', '/')
        if ((Get-FullPath $actualSource) -ne $expectedSource) {
            throw "Package '$id' $($Pin.PackageVersion) was restored from '$actualSource' instead of the verified upstream feed '$expectedSource'."
        }
        $checked++
    }

    $missingRequired = @($Pin.RequiredPackages | Where-Object {
        -not (Test-Path -LiteralPath (Join-Path $PackageCachePath $_.ToLowerInvariant() $Pin.PackageVersion.ToLowerInvariant()) -PathType Container)
    })
    if ($missingRequired.Count -ne 0) {
        throw "Required upstream packages were not restored at $($Pin.PackageVersion): $($missingRequired -join ', ')."
    }
    if ($checked -eq 0) {
        throw "No upstream packages at $($Pin.PackageVersion) were found in '$PackageCachePath'; provenance could not be proven."
    }

    Write-Host "Provenance verified: $checked upstream package(s) at $($Pin.PackageVersion) came from the verified feed."
}

function Remove-Tree {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string] $Path
    )

    # NuGet marks extracted package files read-only, which blocks Remove-Item -Force.
    foreach ($item in @(Get-ChildItem -LiteralPath $Path -Recurse -Force -File -ErrorAction SilentlyContinue)) {
        if ($item.Attributes -band [System.IO.FileAttributes]::ReadOnly) {
            $item.Attributes = $item.Attributes -bxor [System.IO.FileAttributes]::ReadOnly
        }
    }

    Remove-Item -LiteralPath $Path -Recurse -Force
}

function Invoke-Clean {
    [CmdletBinding()]
    param()

    foreach ($path in @($OverlayPath, $UpstreamRoot)) {
        if (Test-Path -LiteralPath $path) {
            Remove-Tree -Path $path
            Write-Host "Removed '$path'."
        }
    }

    if (Test-Path -LiteralPath $RestoreCacheRoot) {
        # Live MSBuild nodes keep task assemblies loaded from the isolated cache.
        & dotnet build-server shutdown | Out-Null
        try {
            Remove-Tree -Path $RestoreCacheRoot
            Write-Host "Removed '$RestoreCacheRoot'."
        }
        catch {
            Write-Warning "Could not remove the isolated restore cache '$RestoreCacheRoot': $($_.Exception.Message)"
            Write-Warning 'The cache does not affect package source selection and is rebuilt by the next Locked restore.'
        }
    }

    Write-Host 'SmartCache now restores from the committed corporate proxy configuration only.'
}

if ($Mode -eq 'Clean') {
    Invoke-Clean
    return
}

$pin = Get-UpstreamPin -Path (Join-Path $PSScriptRoot 'upstream-releases.json') -Name $RequestedName
Assert-PinnedVersionProperty -Pin $pin

$feed = Get-UpstreamFeed -Pin $pin -DestinationRoot $UpstreamRoot -FromDirectory $RequestedFromDirectory -Force:$RequestedForce
$proxy = Get-CorporateProxySource -Path $RootConfigPath
Write-UpstreamOverlay -Path $OverlayPath -FeedPath $feed.Path -Pin $pin -Proxy $proxy

$arguments = @($SolutionPath, '--verbosity', 'minimal')
$packageCachePath = $null
$previousPackages = $env:NUGET_PACKAGES

if ($Mode -eq 'Update') {
    $arguments += '--force-evaluate'
    $packageCachePath = if ([string]::IsNullOrWhiteSpace($env:NUGET_PACKAGES)) {
        Join-Path ([System.Environment]::GetFolderPath('UserProfile')) '.nuget' 'packages'
    }
    else {
        $env:NUGET_PACKAGES
    }
}
else {
    $packageCachePath = Join-Path $RestoreCacheRoot $pin.SourceTag
    $null = New-Item -ItemType Directory -Path $packageCachePath -Force
    $env:NUGET_PACKAGES = Get-FullPath $packageCachePath
    $arguments += @('--configfile', $OverlayPath, '--locked-mode', '--no-http-cache')
}

try {
    Write-Host "Restoring in $Mode mode."
    & dotnet restore @arguments
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet restore failed with exit code $LASTEXITCODE."
    }

    Assert-UpstreamProvenance -PackageCachePath $packageCachePath -FeedPath $feed.Path -Pin $pin
}
finally {
    $env:NUGET_PACKAGES = $previousPackages
}

Write-Host ''
Write-Host "Upstream     : $($pin.Repository) $($pin.SourceTag)"
Write-Host "Version      : $($pin.PackageVersion)"
Write-Host "Feed         : $($feed.Path)"
Write-Host "Overlay      : $OverlayPath"
Write-Host "Restore mode : $Mode"
Write-Host "Package cache: $packageCachePath"
