# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GetAssemblyVersion

on:
  workflow_call:
    # inputs:
    #   config-path:
    #     required: false
    #     type: string
    outputs:
      assemblyVersion:
        description: "assembly Version for the current build"
        value: ${{ jobs.getAssemblyVersion.outputs.assemblyVersion }}
    secrets:
      NUGET_API_KEY:
        required: false
      # token:
      #   required: true

jobs:
  getAssemblyVersion:
    runs-on: self-hosted
    outputs:
      assemblyVersion: ${{ steps.set_assembly_version.outputs.assemblyVersion }}

    env:  # Define environment variables here
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
    ################################
    # build number and version
    - name: Set build number
      id: set_build_number
      run: |
        $env:BUILD_NUMBER="${{ github.run_number }}"
        Write-Host "BUILD_NUMBER=$env:BUILD_NUMBER"
        echo "BUILD_NUMBER=$env:BUILD_NUMBER" >> $GITHUB_ENV
        echo "::set-output name=BUILD_NUMBER::$env:BUILD_NUMBER"
    
    - name: Set Assembly Version
      id: set_assembly_version
      run: |
        Write-Host "set_build_number.outputs.BUILD_NUMBER: ${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        $env:BUILD_NUMBER="${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        Write-Host "env:BUILD_NUMBER: $env:BUILD_NUMBER"
        $env:ASSEMBLY_VERSION="0.9.0.$env:BUILD_NUMBER"
        echo "assemblyVersion=$env:ASSEMBLY_VERSION" >> $GITHUB_OUTPUT

    # - name: Run pwsh Dump Variables
    #   run: |
    #     pwsh -File "scripts/v2/00. DumpVariables.ps1"

    # - name: Dump contexts
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #     JOB_CONTEXT: ${{ toJson(job) }}
    #     STEPS_CONTEXT: ${{ toJson(steps) }}
    #     RUNNER_CONTEXT: ${{ toJson(runner) }}
    #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
    #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
    #     ENV_CONTEXT: ${{ toJson(env) }}
    #     VARS_CONTEXT: ${{ toJson(vars) }}
    #     SECRETS_CONTEXT: ${{ toJson(secrets) }}
    #     NEEDS_CONTEXT: ${{ toJson(needs) }}
    #     INPUTS_CONTEXT: ${{ toJson(inputs) }}
    #   run: |
    #     echo "$GITHUB_CONTEXT"
    #     echo "$env:GITHUB_CONTEXT" >> 01.GITHUB_CONTEXT.log
    #     echo "$JOB_CONTEXT"
    #     echo "$env:JOB_CONTEXT" >> 02.JOB_CONTEXT.log
    #     echo "$STEPS_CONTEXT"
    #     echo "$env:STEPS_CONTEXT" >> 03.STEPS_CONTEXT.log
    #     echo "$RUNNER_CONTEXT"
    #     echo "$env:RUNNER_CONTEXT" >> 04.RUNNER_CONTEXT.log
    #     echo "$STRATEGY_CONTEXT"
    #     echo "$env:STRATEGY_CONTEXT" >> 05.STRATEGY_CONTEXT.log
    #     echo "$MATRIX_CONTEXT"
    #     echo "$env:MATRIX_CONTEXT" >> 06.MATRIX_CONTEXT.log
    #     echo "$ENV_CONTEXT"
    #     echo "$env:ENV_CONTEXT" >> 07.ENV_CONTEXT.log
    #     echo "$VARS_CONTEXT"
    #     echo "$env:VARS_CONTEXT" >> 08.VARS_CONTEXT.log
    #     echo "$SECRETS_CONTEXT"
    #     echo "$env:SECRETS_CONTEXT" >> 10.SECRETS_CONTEXT.log
    #     echo "$NEEDS_CONTEXT"
    #     echo "$env:NEEDS_CONTEXT" >> 11.NEEDS_CONTEXT.log
    #     echo "$INPUTS_CONTEXT"
    #     echo "$env:INPUTS_CONTEXT" >> 12.INPUTS_CONTEXT.log
    # #- name: Dump jobs context
    # #  env:
    # #    JOBS_CONTEXT: ${{ toJson(jobs) }}
    # #  run: |
    # #    echo "$JOBS_CONTEXT"
    # #    echo "$env:JOBS_CONTEXT" >> 09.JOBS_CONTEXT.log
    
