# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Common.SmartCache Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    env:  # Define environment variables here
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      SAMPLE_SECRET: ${{ secrets.SAMPLESECRET }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup NuGet.exe for use with actions
      id: setup_nuget
      uses: NuGet/setup-nuget@v1.2.0
    
    # - name: Install PowerShell Core
    #   id: install_powershell_core
    #   run: |
    #     Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi -OutFile powershell.msi
    #     Start-Process msiexec.exe -Wait -ArgumentList '/i powershell.msi /quiet /norestart'
    #     Write-Host "powershell.msi install completed"

    - name: Run pwsh Dump
      run: |
        pwsh -File "scripts/v2/00. DumpVariables.ps1"

    - name: Set build number
      id: set_build_number
      run: |
        $env:BUILD_NUMBER="${{ github.run_number }}"
        Write-Host "BUILD_NUMBER=$env:BUILD_NUMBER"
        echo "SampleSecret=${{ secrets['SampleSecret'] }}" >> SECRETS.txt
        echo "BUILD_NUMBER=$env:BUILD_NUMBER" >> $GITHUB_ENV
        echo "::set-output name=BUILD_NUMBER::$env:BUILD_NUMBER"
    
    - name: Set Assembly Version
      run: |
        Write-Host "set_build_number.outputs.BUILD_NUMBER: ${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        $env:BUILD_NUMBER="${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        Write-Host "env:BUILD_NUMBER: $env:BUILD_NUMBER"
        $env:ASSEMBLY_VERSION="1.0.0.$env:BUILD_NUMBER"
        Write-Host "Setting assembly version to: $env:ASSEMBLY_VERSION"
        (Get-Content Common.SmartCache/Common.SmartCache.csproj) -replace '<Version>.*<\/Version>', "<Version>$env:ASSEMBLY_VERSION</Version>" | Set-Content Common.SmartCache/Common.SmartCache.csproj

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build DLL
      run: dotnet build Common.SmartCache/Common.SmartCache.csproj --configuration Release --no-restore #--verbosity detailed
      
    - name: Upload bin folder as an Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact
        path: |
          Common.SmartCache/bin/
          !Common.SmartCache/bin/**/*.tmp
        if-no-files-found: warn
        retention-days: 1
    
    # - name: Publish DLL
      #   run: dotnet publish Common.SmartCache/Common.SmartCache.csproj --configuration Release --output ./publish --no-build

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: dll-artifact
      #    path: ./publish

      #- name: Create NuGet package
      #  run: dotnet pack --no-build --include-symbols -o ./nupkg
      #  working-directory: ./Common.SmartCache/bin/Debug

      # - name: Publish NuGet package
      #   uses: nuget/publish@1.0.0
      #   with:
      #     nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      #     nuget-version: 'latest'

    - name: Test
      run: dotnet test --no-build --verbosity normal
