# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Common.SmartCache Package Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    env:  # Define environment variables here
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      SAMPLE_SECRET: ${{ secrets.SAMPLESECRET }}

    steps:
    - uses: actions/checkout@v3
    ################################
    # setup steps
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet.exe for use with actions
      id: setup_nuget
      uses: NuGet/setup-nuget@v1.2.0
    
    # - name: Install PowerShell Core
    #   id: install_powershell_core
    #   run: |
    #     Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi -OutFile powershell.msi
    #     Start-Process msiexec.exe -Wait -ArgumentList '/i powershell.msi /quiet /norestart'
    #     Write-Host "powershell.msi install completed"
    
    ################################
    # dump steps
    - name: Run pwsh Dump Variables
      run: |
        pwsh -File "scripts/v2/00. DumpVariables.ps1"

    #- name: Run pwsh Dump github context1
    #  run: |
    #    pwsh -File "scripts/v2/01. DumpContext.ps1" -context ${{ github.GetType() }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "$env:GITHUB_CONTEXT" >> 01.GITHUB_CONTEXT.txt
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: |
        echo "$JOB_CONTEXT"
        echo "$env:JOB_CONTEXT" >> 02.JOB_CONTEXT.txt
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: |
        echo "$STEPS_CONTEXT"
        echo "$env:STEPS_CONTEXT" >> 03.STEPS_CONTEXT.txt
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
        echo "$RUNNER_CONTEXT"
        echo "$env:RUNNER_CONTEXT" >> 04.RUNNER_CONTEXT.txt
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: |
        echo "$STRATEGY_CONTEXT"
        echo "$env:STRATEGY_CONTEXT" >> 05.STRATEGY_CONTEXT.txt
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        echo "$MATRIX_CONTEXT"
        echo "$env:MATRIX_CONTEXT" >> 06.MATRIX_CONTEXT.txt
    - name: Dump env context
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: |
        echo "$ENV_CONTEXT"
        echo "$env:ENV_CONTEXT" >> 07.ENV_CONTEXT.txt
    - name: Dump vars context
      env:
        VARS_CONTEXT: ${{ toJson(vars) }}
      run: |
        echo "$VARS_CONTEXT"
        echo "$env:VARS_CONTEXT" >> 08.VARS_CONTEXT.txt
    - name: Dump jobs context
      env:
        JOBS_CONTEXT: ${{ toJson(jobs) }}
      run: |
        echo "$JOBS_CONTEXT"
        echo "$env:JOBS_CONTEXT" >> 09.JOBS_CONTEXT.txt
    - name: Dump secrets context
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        echo "$SECRETS_CONTEXT"
        echo "$env:SECRETS_CONTEXT" >> 10.SECRETS_CONTEXT.txt

    ################################
    # build number and version
    - name: Set build number
      id: set_build_number
      run: |
        $env:BUILD_NUMBER="${{ github.run_number }}"
        Write-Host "BUILD_NUMBER=$env:BUILD_NUMBER"
        echo "SampleSecret=${{ secrets['SampleSecret'] }}" >> SECRETS.txt
        echo "BUILD_NUMBER=$env:BUILD_NUMBER" >> $GITHUB_ENV
        echo "::set-output name=BUILD_NUMBER::$env:BUILD_NUMBER"
    
    - name: Set Assembly Version
      run: |
        Write-Host "set_build_number.outputs.BUILD_NUMBER: ${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        $env:BUILD_NUMBER="${{ steps.set_build_number.outputs.BUILD_NUMBER }}"
        Write-Host "env:BUILD_NUMBER: $env:BUILD_NUMBER"
        $env:ASSEMBLY_VERSION="1.0.0.$env:BUILD_NUMBER"
        Write-Host "Setting assembly version to: $env:ASSEMBLY_VERSION"
        (Get-Content Common.SmartCache/Common.SmartCache.csproj) -replace '<Version>.*<\/Version>', "<Version>$env:ASSEMBLY_VERSION</Version>" | Set-Content Common.SmartCache/Common.SmartCache.csproj

    ################################
    # restore and build
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build DLL
      run: dotnet build Common.SmartCache/Common.SmartCache.csproj --configuration Release --no-restore #--verbosity detailed
      
    ################################
    # upload artifacts
    - name: Upload bin folder as an Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact
        path: |
          Common.SmartCache/bin/
          !Common.SmartCache/bin/**/*.tmp
        if-no-files-found: warn
        retention-days: 1
    
    # - name: Publish DLL
      #   run: dotnet publish Common.SmartCache/Common.SmartCache.csproj --configuration Release --output ./publish --no-build

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: dll-artifact
      #    path: ./publish

      #- name: Create NuGet package
      #  run: dotnet pack --no-build --include-symbols -o ./nupkg
      #  working-directory: ./Common.SmartCache/bin/Debug

      # - name: Publish NuGet package
      #   uses: nuget/publish@1.0.0
      #   with:
      #     nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      #     nuget-version: 'latest'

    ################################
    # test
    - name: Test
      run: dotnet test --no-build --verbosity normal
